Debug retry step when nightly build is copy failed
Signed-off-by: Xiaodong Li <xiaodong.li@intel.com>

diff --git a/.github/workflows/ci_lin.yml b/.github/workflows/ci_lin.yml
--- a/.github/workflows/ci_lin.yml
+++ b/.github/workflows/ci_lin.yml
@@ -59,11 +59,15 @@ jobs:
           git reset ${DATE_YESTERDAY} --hard
 
       - name: Get_Latest_Nightly
-        shell: bash
-        run: |
-          ARCHIVE_PATH=$(cat $GITHUB_WORKSPACE/../../../../GH_CI_LIN_ARCHIVE_FOLDER.txt)
-          find $ARCHIVE_PATH -maxdepth 1 -type d -name "*_*0000" -print | sort -r | head -1 |xargs -i cp -r "{}/build/linux_prod/" ./                                           
-          mv linux_prod c2s.obj
+        uses: nick-fields/retry@v2
+        with:
+          max_attempts: 10 
+          retry_wait_seconds: 30
+          shell: bash
+          command: |
+            ARCHIVE_PATH=$(cat $GITHUB_WORKSPACE/../../../../GH_CI_LIN_ARCHIVE_FOLDER.txt)
+            find $ARCHIVE_PATH -maxdepth 1 -type d -name "*_*0000" -print | sort -r | head -1 |xargs -i cp -r "{}/build/linux_prod/" ./                                           
+            mv linux_prod c2s.obj
 
       - name: Prepare Env
         timeout-minutes: 60
@@ -71,20 +75,20 @@ jobs:
         with:
           c2s_obj_dir: "c2s.obj"
         
-      - name: Run testing option_cpu
-        timeout-minutes: 180
-        shell: bash
-        run: |
-          cd c2s_test_repo
-          time python run_test.py --suite ${{ matrix.test_suite }} --option option_cpu
-          echo $PWD
+            #- name: Run testing option_cpu
+            #  timeout-minutes: 180
+            #  shell: bash
+            #  run: |
+            #    cd c2s_test_repo
+            #    time python run_test.py --suite ${{ matrix.test_suite }} --option option_cpu
+            #    echo $PWD
 
-      - name: Run testing option_usmnone_cpu
-        if: success() || failure()
-        timeout-minutes: 180
-        shell: bash
-        run: |
-          cd c2s_test_repo
-          time python run_test.py --suite ${{ matrix.test_suite }} --option option_usmnone_cpu
-          echo $PWD
+            #- name: Run testing option_usmnone_cpu
+            #  if: success() || failure()
+            #  timeout-minutes: 180
+            #  shell: bash
+            #  run: |
+            #    cd c2s_test_repo
+            #    time python run_test.py --suite ${{ matrix.test_suite }} --option option_usmnone_cpu
+            #    echo $PWD
 
